### ISSUE TITLE
[Bug]: Tests not executed on latest NodeJS release

### ISSUE THREAD

**Issue by doosuu** [eclipse-velocitas/cli#141]
### Severity

Medium

### What release version, tag or commit-hash did you use?

v0.5.2

### Current Behavior

Tests are not executed on latest NodeJS release (at the state of writing 20.5.0) because of an issue in mock-fs module:
https://github.com/tschaub/mock-fs/issues/377

Once that is released, we need to fix our CI.yml to use latest again.

### Steps to Reproduce

Execute CI workflow

### Expected Behavior

Workflow runs using latest NodeJS release

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by dennismeister93** [comment]
Not longer necessary due to removal of mock-fs: https://github.com/eclipse-velocitas/cli/pull/221
