### ISSUE TITLE
[Bug]: AppName is not properly set when using "create" command

### ISSUE THREAD

**Issue by MP91** [eclipse-velocitas/cli#169]
### Severity

Trivial

### What release version, tag or commit-hash did you use?

v0.6.3

### Current Behavior

When calling velocitas create without an example, a project name has to be chosen. Unfortunately this name is not set as AppName in the Python code.

### Steps to Reproduce

1. velocitas create -n testApp -l python
2. check main.py or vapp.py

### Expected Behavior

AppName is properly set in python scripts

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by dennismeister93** [comment]
will be solved with https://github.com/eclipse-velocitas/cli/pull/199

**Comment by dennismeister93** [comment]
Fixed with #212
