### ISSUE TITLE
[Bug]: velocitas init has a hard dependency to DAPR / Docker environment and fails inside of a docker build

### ISSUE THREAD

**Issue by mikehaller** [eclipse-velocitas/cli#173]
### Severity

Medium

### What release version, tag or commit-hash did you use?

Unsure about CLI version, but it prints: devenv-runtimes:v2.2.3

### Current Behavior

We're trying to build the seat adjuster example applications inside of a Dockerfile GitHub Actions build.

Unfortunately, the build errors out at the "velocitas init" step:
https://github.com/eclipse-leda/leda-example-applications/actions/runs/7007108396/job/19060442384

```
 #21 6.490 #######################################################
#21 6.490 ### Ensure dapr                                     ###
#21 6.490 #######################################################
#21 6.491 /root/.velocitas/packages/devenv-runtimes/v2.2.3/runtime_local/src/ensure-dapr.sh: line 35: dapr: command not found
#21 6.493 /root/.velocitas/packages/devenv-runtimes/v2.2.3/runtime_local/src/ensure-dapr.sh: line 36: dapr: command not found
#21 6.495 Install dapr CLI 1.10.0
#21 6.663 Your system is linux_amd64
#21 6.663 Installing Dapr CLI...
#21 6.663 
#21 6.663 Installing v1.10.0 Dapr CLI...
#21 6.664 Downloading https://github.com/dapr/cli/releases/download/v1.10.0/dapr_linux_amd64.tar.gz ...
#21 8.519 dapr installed into /usr/local/bin successfully.
#21 8.544 CLI version: 1.10.0 
#21 8.544 Runtime version: n/a
#21 8.569 
#21 8.569 To get started with Dapr, please visit https://docs.dapr.io/getting-started/
#21 8.570 Initialize dapr runtime 1.10.3 ...
#21 8.595 ℹ️  Removing Dapr from your machine...
#21 8.595 ⚠  WARNING: /root/.dapr/bin does not exist
#21 8.595 ✅  Dapr has been removed successfully
#21 8.625 ⌛  Making the jump to hyperspace...
#21 8.625 ❌  could not connect to Docker. Docker may not be installed or running
#21 8.633     ExecExitError: Program returned exit code: 1
#21 ERROR: process "/bin/sh -c velocitas init --verbose" did not complete successfully: exit code: 1
```

The build script and Dockerfile is located here:
https://github.com/eclipse-leda/leda-example-applications/tree/main/seat-adjuster

### Steps to Reproduce

1. Run https://github.com/eclipse-leda/leda-example-applications/blob/main/.github/workflows/docker-build-publish-seatadjuster.yml
2. Alternatively, run a docker build with build-docker.sh from https://github.com/eclipse-leda/leda-example-applications/tree/main/seat-adjuster - it may result in the same error, but not yet tested/reproduced.

### Expected Behavior

"velocitas init" does not relay on DAPR and does not rely on connecting to a Docker daemon.

### Possible Solution

Add a "Skip Ensure-DAPR task" option, so that we can build the velocitas application without the need of the DAPR installation inside of the Docker build environment. (as there is also no Kubernetes running...)

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by BjoernAtBosch** [comment]
"Solved" by removing support of Dapr middleware from Velocitas.
Related issues:
https://github.com/eclipse-velocitas/vehicle-app-python-template/issues/233
https://github.com/eclipse-velocitas/vehicle-app-cpp-template/issues/92
https://github.com/eclipse-velocitas/vehicle-app-template/issues/10
https://github.com/eclipse-velocitas/vehicle-app-python-sdk/issues/121
https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/issues/85
https://github.com/eclipse-velocitas/devenv-devcontainer-setup/issues/59
https://github.com/eclipse-velocitas/devenv-runtimes/issues/68
https://github.com/eclipse-velocitas/devenv-github-workflows/issues/52
