### ISSUE TITLE
[Bug]: errors during velocitas init are not recognized/persistent

### ISSUE THREAD

**Issue by MP91** [eclipse-velocitas/cli#174]
### Severity

Medium

### What release version, tag or commit-hash did you use?

v0.6.3

### Current Behavior

When running velocitas init it might happen that one step fails. No issue, but if you run the command again, it assumes that the package with the error is already correctly initialized and just continues with the next one.

The one with the error is not completely initialized and can't be used. 

### Steps to Reproduce

run velocitas init

### Expected Behavior

Errors are recognized and packages with errors are not set to properly installed.

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by dennismeister93** [comment]
Fixed with https://github.com/eclipse-velocitas/cli/pull/212
