### ISSUE TITLE
[Bug]: Path to the AppManifest is not configurable

### ISSUE THREAD

**Issue by MP91** [eclipse-velocitas/cli#205]
### Severity

Medium

### What release version, tag or commit-hash did you use?

v0.6.3

### Current Behavior

In the velocitas.json one could set the "appManifestPath", but this is not recognized by the cli. 

Whenever a path different to app/AppManifest.json is used, the cli can not find the AppManifest.

### Steps to Reproduce

1. put AppManifest somewhere different to app/AppManifest.json
2. adapt the variable in velocitas.json
3. run 'velocitas init'
4. see "AppManifest not found" in the log

### Expected Behavior

correct path is used

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by dennismeister93** [comment]
Fixed with #212
