### ISSUE TITLE
add `create` command to directly create a repository locally

### ISSUE THREAD

**Issue by MP91** [eclipse-velocitas/cli#65]
The https://github.com/eclipse-velocitas/cli shall be extended to provide a new command:

`new --lang <programming_language> --name <vehicle_app_name>`

This command shall create a new vehicle app project.
This is shall be done by applying the following steps:

1. Download respective SDK's latest release as archive
1. Unzip the archive to a temp directory
1. Read the `.velocitas.json` of the SDK - it should contain a list of all exposed examples as part of its variables, e.g.
`"variables": {
      "exposedExamples": [
          {
              "name": "Seat Adjuster",
              "path": "./examples/seat-adjuster"
          }
      ]
}`

1. The user of the CLI is prompted which example he wants to use as base project
1. Create a new project directory with the user provided name
1. Prompt the user which Velocitas CLI packages he wants to include in his project and create a new `.velocitas.json` for the project using that output.
1. Copy the contents of the chosen example into the new project
1. invoke `velocitas sync` to create the initial content of the repo
1. <identify which files are still missing to create the project and decide on a way to include them, e.g. further variables in the SDK?>

Stretch goal:

If the new command is done and tests are available for new code, a new workflow for our template repos can be introduced which runs this new command and creates a pull request if it detects a difference between the template and the fresh project - similar to dependabot. This will help us to keep the templates up2date even if we just work on the SDK projects in the future

Wip branch: https://github.com/eclipse-velocitas/cli/tree/new-command

**Comment by doosuu** [comment]
Already implemented with #162
